---
title: "MethComp"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(gridExtra)
  library(dplyr)
})
theme_set(theme_classic())
```

```{r}
width <- 8  # inches
height <- 4  # inches
dpi <- 400
```

## runATAC

Load readouts

```{r}
lf <- list.files(pattern="^BM.+rds", full=TRUE) # obtain list of files in the directory "results". ^BM.+rds means that the file names must start with "BM" and end with ".rds", and can have any characters in between.
names(lf) <- gsub("BM|\\.rds","",basename(lf)) # The basename() function extracts the file names from the full file paths in the lf list.
res <- lapply(lf, FUN=readRDS)
```

# Rank

```{r}
ranks <- dplyr::bind_rows(lapply(res, FUN=function(x){
  dplyr::bind_rows(lapply(x$true_rank_table, as.data.frame), .id="Method")
}), .id="Dataset")
ranks$rank <- as.integer(ranks$rank)

mean_rank_sqrt <- function(x) {
  mean(sqrt(x))
}


namechange <- c() 
namechange$old <- c("ulm", "CVnorm", "GSEA", "dRconsensus", "MLStabSel", "regreg")
namechange$new <- c("ULM", "CVadj", "FGSEA", "decouple", "StabSel", "Regreg")

ranks <- ranks %>% 
  mutate(Method = case_when(
    Method %in% namechange$old ~ namechange$new[match(Method, namechange$old)],
    TRUE ~ Method
  ))

Iwant <- c("CV", "ULM", "FGSEA", "decouple", "StabSel", "Regreg", "msVIPER", "VIPER", "ML")
ranks <- subset(ranks, ranks$Method %in% Iwant)

ranks$Method <- reorder(ranks$Method, ranks$rank, mean_rank_sqrt)
ranks$Dataset <- reorder(ranks$Dataset, ranks$rank, mean_rank_sqrt)

rankplot <- ggplot(ranks, aes(Method, Dataset, fill=rank, label=rank)) + 
  geom_tile() + 
  geom_text() + 
  labs(fill="Rank")+
  theme_minimal()+
  scale_fill_viridis_c(direction = -1, trans="log", breaks=c(1,7,15,50,400))
rankplot
ggsave("./Plots/runATACranks.png", width = width, height = height, dpi = dpi)
```

```{r}
rank_data <- ranks %>%
  mutate(sqrt_rank = sqrt(rank))

method_means <- rank_data %>%
  group_by(Method) %>%
  summarize(mean_sqrt_rank = mean(sqrt_rank))

write.csv(method_means, "method_means.csv")
```


# adjusted pvalues

```{r}
adj_pval <- dplyr::bind_rows(lapply(res, FUN=function(x){
  dplyr::bind_rows(lapply(x$true_padj, as.data.frame), .id="Method")
}), .id="Dataset")
names(adj_pval)[3] <- "adj_pval"
adj_pval$adj_pval <- round(adj_pval$adj_pval, 2)
padjplot <- ggplot(adj_pval, aes(Method, Dataset, fill=adj_pval, label=adj_pval)) + geom_tile() + 
  geom_text() + scale_fill_viridis_c(direction = -1)
padjplot
```

# AUC

```{r}
AUCs <- dplyr::bind_rows(lapply(res, FUN=function(x){
  dplyr::bind_rows(lapply(x$relAUC,as.data.frame), .id="Method")
}), .id="Dataset")
colnames(AUCs)[3] <- "relAUC"

mean_AUC <- function(x) {
  (mean(x))
}

AUCs <- AUCs %>% 
  mutate(Method = case_when(
    Method %in% namechange$old ~ namechange$new[match(Method, namechange$old)],
    TRUE ~ Method
  ))

AUCs <- subset(AUCs, AUCs$Method %in% Iwant)

AUCs$Method <- reorder(AUCs$Method, AUCs$relAUC, mean_AUC)
AUCs$Dataset <- reorder(AUCs$Dataset, AUCs$relAUC, mean_AUC)

AUCplot <- ggplot(AUCs, aes(Method, Dataset, fill=relAUC, label=relAUC)) + 
  geom_tile() + 
  geom_text() + 
  labs(fill="RelAUC")+
  theme_minimal()+
  scale_fill_viridis_c()
AUCplot
ggsave("./Plots/runATACAUCs.png", width = width, height = height, dpi = dpi)
```


```{r}
sf <- dplyr::bind_rows(lapply(res, FUN=function(x){
  x <- cbind(x$padj, FD=unlist(x$FD), notTF=unlist(x$NotTrueTF))
  x$sensitivity <- as.numeric((x$padj)<=0.05)
  isDiscovered <- ifelse(x$padj<=0.05, 1,0)
  x$FDR <- x$FD/(isDiscovered+x$notTF) # only works for single gene datasets
  x$FDR <- fifelse(is.nan(x$FDR),0,x$FDR)
  x
}), .id="Dataset")
ag <- aggregate(sf[,c("sensitivity","FDR")], by=sf[,"method",drop=FALSE], FUN=mean)

ag <- ag %>% 
  mutate(method = case_when(
    method %in% namechange$old ~ namechange$new[match(method, namechange$old)],
    TRUE ~ method
  ))

agmS <- readRDS("FDR_Sensitivity_StabSel")

ag <- rbind(ag, agmS)

# write.csv(ag, file = "agfull.csv", row.names = FALSE)

FDRplot <- ggplot(ag, aes(FDR, sensitivity, label=method)) + geom_point() +
  ggrepel::geom_text_repel(min.segment.length = 0)+
  ylab("Sensitivity")
FDRplot
ggsave("./Plots/runATACFDR.png", width = 8, height = height, dpi = dpi)
```
