---
title: "MBATEST"
author: "Felix Gerbaldo"
date: "21 7 2023"
output: html_document
---

```{r}
source("/mnt/plger/fgerbaldo/DTFAIB/Scripts/runBaGFoot.R")
source("/mnt/plger/fgerbaldo/DTFAIB/Scripts/runATAC.R")

pmoi <- readRDS("./runATAC_results/others/pmoi.rds")
readlist <- c(list.files("./seq_files", pattern="bed$", full=TRUE))

se.mba <- getModelBasedActivity(readlist, pmoi, paired=TRUE, BPPARAM=MulticoreParam(6, progress=TRUE))
saveRDS(se.mba, "MBA_rawres")

se.mba <- readRDS("MBA_rawres")

# differential analysis... same as chromVAR and the likes:
 dds <- calcNormFactors(DGEList(assay(se.mba)))
 groups <- rep(LETTERS[1:2],each=3)
 design <- model.matrix(~groups)
 fit <- eBayes(lmFit(voom(dds, design), design))
 topTFs <- topTable(fit, number = Inf)
```

```{r}
if ("MBA" %in$% methods){
  set.seed(rndSeed)
  
}
```

```{r}
runMBA <- function(readlist,
           pmoi,
           paired_arg){
  ptm <- proc.time()
  se.mba <- getModelBasedActivity(readlist, 
                                  pmoi, 
                                  paired_arg, 
                                  BPPARAM=MulticoreParam(6, progress=TRUE))
  runtime <- proc.time()-ptm
  dds <- calcNormFactors(DGEList(assay(se.mba)))
  groups <- rep(LETTERS[1:2],each=3)
  design <- model.matrix(~groups)
  fit <- eBayes(lmFit(voom(dds, design), design))
  topTFs <- topTable(fit, number = Inf)
  return(list(topTFs, runtime, fit, se.mba))
           }
```

